from abc import ABC, abstractmethod
class BaseConnector(ABC):
    @abstractmethod
    def authenticate(self, **kwargs): ...
    @abstractmethod
    def list_files(self): ...
    @abstractmethod
    def get_file_metadata(self, file_id): ...
    @abstractmethod
    def download_file(self, file_id): ...
    @abstractmethod
    def disconnect(self): ...
